### ISSUE TITLE
Wrong Citation

### ISSUE THREAD

**Issue by rishin27** [lucidrains/axial-positional-embedding#2]
Hi @lucidrains 

I'm not sure why "Axial Attention in Multidimensional Transformers" paper is cited. This repo is an implementation of axial positional encoding (i.e. factorizing  of the positional embedding matrix), whereas the paper talks about axial based attention mechanism.

Reference - https://huggingface.co/transformers/model_doc/reformer.html

Thanks,

**Comment by lucidrains** [comment]
@rishin27 ohh true, let me cite the Reformer folks
